#!/bin/bash

COLOR_NONE='\033[0m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[1;34m'

if [ -z "$1" ]; then
	printf "${COLOR_YELLOW}\nPlease Provide a msgid String.\n${COLOR_NONE}"
	exit 1
fi

ls -1 ~/plasmasnow/po/*.po | sort > app
cat app | sed -n -e 's/^.*\///p' > appclean

ls -1 *.po | sort > avail

# Remove files avail but unwanted.
for f in $(join -v2 appclean avail); do \
	rm -f $f; \
done;

# Apply final additions to app.
for f in $(ls -1 *.po); do \
	printf "   updating: ${COLOR_BLUE}~/plasmasnow/po/$f.\n${COLOR_NONE}" && \
	echo "msgid ""\""$1"\"" >> ~/plasmasnow/po/$f && \
	cat $f >> ~/plasmasnow/po/$f; \
done
