#!/bin/bash

COLOR_NONE='\033[0m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[1;34m'

if [ -z "$1" ]; then
	printf "${COLOR_YELLOW}\nPlease Provide a msgid String.\n${COLOR_NONE}"
	exit 1
fi

ls -1 ~/plasmasnow/po/*.po 2>/dev/null | sort > appFiles
cat appFiles | sed -n -e 's/^.*\///p' > appCleanFiles

# Remove files avail but unwanted.
ls -1 *.po 2>/dev/null | sort > availFiles
for f in $(join -v2 appCleanFiles availFiles); do \
	printf "${COLOR_YELLOW}\nRemoved, unused LINGUA.\n${COLOR_NONE}"
	rm -f $f
done
if [[ $(sed -n '$=' availFiles) == "" ]]; then
	printf "${COLOR_YELLOW}\nNo unused LINGUAs removed.\n${COLOR_NONE}"
fi

# Remove files wanted and avail, but already translated.
ls -1 *.po 2>/dev/null | sort > availAppFiles

ALREADY_TRANSLATED=""
for f in $(cat availAppFiles)
do
	cat $f | egrep "\""$1"\"" 1>/dev/null 2>/dev/null && \
		ALREADY_TRANSLATED=$?
	if [ $ALREADY_TRANSLATED == "1" ]; then
		printf "${COLOR_YELLOW}\nRemoved, LINGUA already translated.\n${COLOR_NONE}"
		rm -f $f
	fi		
done
if [[ $(sed -n '$=' availAppFiles) == "" ]]; then
	printf "${COLOR_YELLOW}\nNo already translated LINGUAs removed.\n${COLOR_NONE}"
fi
